- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql server
    ansible.builtin.server:
      name: mysqld
      state: started
      enabled: yes